apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev  
  template:
    metadata:
      name: firstpod
      labels:
        env: dev
    spec:
      containers:
      - image: yash8808/django
        name: fist
