apiVersion: v1
kind: Pod
metadata:
  name: ebs2
  labels:
    env: dev
spec:
  containers:
    - image: yash8808/django
      name: first
      volumeMounts:
            - mountPath: /data
              name: testebs
  volumes:
    - name: testebs
      awsElasticBlockStore:
        fsType: ext4
        volumeID: "vol-06103da703079a7f3"