apiVersion: v1
kind: Pod
metadata:
  name: volume2
  labels:
    env: dev
spec:
  containers:
    - image: yash8808/django
      name: first
      volumeMounts:
            - mountPath: /data
              name: first-volume
  volumes:
    - name: first-volume
      hostPath:
        path: /tmp/data