apiVersion: v1
kind: LimitRange
metadata:
  name: limit
  namespace: test
spec:
  limits:
    - default:
        cpu: 200m
        memory: 500Mi
      defaultRequest:
        cpu: 100m
        memory: 250Mi
      min:
        cpu: 80m
        memory: 200Mi
      max:
        cpu: 300m
        memory: 750Mi
      type: Container