apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
spec:
  replicas: 5
  template:
    metadata:
      name: firstpod
      labels:
        env: dev
    spec:
      containers:
      - image: yash8808/django
        name: fist
