apiVersion: v1
kind: Pod
metadata:
  name: resource
  #namespace: test
  labels:
    env: dev
spec:
  containers:
    - image: yash8808/django
      name: fist
      resources:
        requests:
          memory: 200Mi
          cpu: 100m
        limits:
          memory: 500Mi
          cpu: 200m


